version: "3.9"

services:
  # ============================================================
  # 🗄️ PostgreSQL Database
  # ============================================================
  jj_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Manila
    ports:
      - "5432:5432"
    volumes:
      - jj_db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ============================================================
  # ⚙️ FastAPI Backend (JJNotificationService)
  # ============================================================
  jjnotificationservice:
    build:
      context: ./JJNotificationService
      dockerfile: Dockerfile
    container_name: jjnotificationservice
    restart: always
    depends_on:
      jj_db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: jj_db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ENV: docker
      TZ: Asia/Manila
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    entrypoint: ["/entrypoint.sh"]

    # 🩺 Improved Healthcheck — gives backend time for migrations + MikroTik init
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health | grep -q 'ok' || exit 1"]
      interval: 20s      # check every 20s
      timeout: 10s       # allow 10s response time
      retries: 15        # 15 attempts (≈5 mins total)
      start_period: 120s # ⏳ allow 2 mins before first check

  # ============================================================
  # 🧭 pgAdmin (Database GUI)
  # ============================================================
  jj_pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: Asia/Manila
    ports:
      - "5050:80"
    depends_on:
      jj_db:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # ============================================================
  # 🌐 Frontend (JJNotificationApp)
  # ============================================================
  jjnotificationapp:
    build:
      context: ./JJNotificationApp
      dockerfile: Dockerfile
    container_name: jjnotificationapp
    restart: always
    depends_on:
      jjnotificationservice:
        condition: service_healthy   # wait until FastAPI backend ready
    ports:
      - "80:80"
    volumes:
      - ./JJNotificationApp/nginx.conf:/etc/nginx/conf.d/default.conf:ro

# ============================================================
# 🗃️ Volumes
# ============================================================
volumes:
  jj_db_data:
