version: "3.9"

services:
  jjnotificationapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: jjnotificationapp
    restart: always
    ports:
      - "5173:80"
    env_file:
      - ../.env   # reuse the root .env
